Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "detect_face_sms.py", line 39, in classify_frame
    faces = face_cascade.detectMultiScale(gray, 1.1, 4)
  File "detect_face_sms.py", line 25, in signal_handler
    with writer:
AttributeError: __enter__
